const bcrypt = require('bcryptjs');

const data = {
  users: [
    {
      name: 'Admin',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      role: 'admin',
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      role: 'user',
    },
    {
      name: 'John Slim',
      email: 'slim@example.com',
      password: bcrypt.hashSync('123456'),
      role: 'vendor',
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'Men\'s Briefs',
      slug: 'men\'s-briefs',
      category: 'Shirts',
      image: '/images/p1.jpg', // 679px × 829px
      price: 1000,
      countInStock: 10,  
      brand: 'Generic',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      // _id: '2',
      name: 'Blue Shirt',
      slug: 'blue-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 2000,
      countInStock: 1,
      brand: 'Generic',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      // _id: '3',
      name: 'Red Gown',
      slug: 'red-gown',
      category: 'Gown',
      image: '/images/p3.jpg',
      price: 2500,
      countInStock: 4,
      brand: 'Generic',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      // _id: '4',
      name: 'Trousers Grey',
      slug: 'trouser-grey',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 4500,
      countInStock: 5,
      brand: 'Generic',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      // _id: '5',
      name: 'Female Gown',
      slug: 'female-gown',
      category: 'Gown',
      image: '/images/p5.jpg',
      price: 2500,
      countInStock: 5,
      brand: 'Generic',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      // _id: '6',
      name: 'Trouser Blue',
      slug: 'trouser-blue',
      category: 'Pants',
      image: '/images/p6.jpg',
      price: 4500,
      countInStock: 5,
      brand: 'Generic',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};

module.exports = data;
