const data = {
  users: [
    {
      name: 'Admin',
      email: 'admin@example.com',
      password: '123456',
      role: 'admin',
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: '123456',
      role: 'user',
    },
    {
      name: 'John Slim',
      email: 'slim@example.com',
      password: '123456',
      role: 'vendor',
    },
  ],
  products: [
    {
      name: "Men's Briefs",
      category: 'Male',
      newArrival: true,
      color: 'Black',
      grade: 'A',
      size: 'M',
      image: '/images/p1.jpg', // 679px × 829px
      price: 1000,
      countInStock: 10,
      brand: 'Generic',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Blue Shirt',
      category: 'Male',
      newArrival: true,
      color: 'Blue',
      grade: 'A',
      size: 'L',
      image: '/images/p2.jpg',
      price: 2000,
      countInStock: 1,
      brand: 'Generic',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Red Gown',
      category: 'Female',
      newArrival: true,
      color: 'Red',
      grade: 'B',
      size: 'L',
      image: '/images/p3.jpg',
      price: 2500,
      countInStock: 4,
      brand: 'Generic',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Trousers Grey',
      category: 'Male',
      newArrival: true,
      color: 'Grey',
      grade: 'B',
      size: 'L',
      image: '/images/p4.jpg',
      price: 4500,
      countInStock: 5,
      brand: 'Generic',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Female Gown',
      category: 'Female',
      newArrival: true,
      color: 'Blue',
      grade: 'A',
      size: 'XL',
      image: '/images/p5.jpg',
      price: 2500,
      countInStock: 5,
      brand: 'Generic',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Trouser Blue',
      category: 'Male',
      newArrival: true,
      color: 'Blue',
      grade: 'B',
      size: 'M',
      image: '/images/p6.jpg',
      price: 4500,
      countInStock: 5,
      brand: 'Generic',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};

module.exports = data;
